##  要創建一個3x3矩陣，其中包含從0到8的值
```python
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```
## 要創建一個3x3的單位矩陣（identity matrix）
```python
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```

In [2]:
import numpy as np
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 要使用 NumPy 生成一個包含25個從標準正態分布（平均值為0，標準差為1的正態分布）抽樣的隨機數陣列

In [8]:
import numpy as np
np.random.randn(25)

array([ 1.33279763,  0.27277578, -0.81222233,  1.10596509,  0.25519466,
        0.58478227,  0.70360177, -1.02334578,  0.09735305, -0.21562274,
        0.63996761, -0.38334272,  0.01799705, -0.74782582,  1.14415779,
        0.18077293, -0.17687728,  0.162571  ,  0.29147225,  0.63861489,
        0.65012341,  1.43433686,  2.65349365,  0.11059548,  1.92175243])

##  要創建一個包含從0到1之間20個等距點的陣列

```python
array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

```

In [10]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## 幫我產生以下的陣列
```ptyhon
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

```

In [12]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## 根據以下輸出完成功能
```python
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [13]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 根據以下輸出完成功能
```python
array([[ 2],
       [ 7],
       [12]])
```

In [17]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [21]:
import numpy as np
arr_1 = np.arange(1,26)
arr_1 = arr_1.reshape(5,5)
#print(arr_1.reshape(5,5))
arr_1[:3 , 1:2]

array([[ 2],
       [ 7],
       [12]])

```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [22]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Series
第一個我們將學習的主要數據類型是Pandas中的Series數據類型。讓我們導入Pandas並探索Series對象。

Series與NumPy陣列非常相似（事實上它是建立在NumPy陣列對象之上的）。將NumPy陣列與Series區分開來的是，Series可以具有軸標籤，這意味著它可以通過標籤進行索引，而不僅僅是通過數字位置。它也不需要保存數字數據，可以保存任意的Python對象。

讓我們通過一些示例來探索這個概念：

In [23]:
import pandas as pd
mindex = ["USA","Canda","Mexico"]
mydata = [1776,1867,1821]
mySer = pd.Series(data=mydata)
mySer

0    1776
1    1867
2    1821
dtype: int64

In [24]:
mySer2 = pd.Series(data=mydata,index=mindex)
mySer2

USA       1776
Canda     1867
Mexico    1821
dtype: int64

In [27]:
ran_data = np.random.randint(0,100,4)
names = ["Ken","Bobo","Iris","Lindy"]
ages = pd.Series(ran_data,names)
ages

Ken      10
Bobo     36
Iris     40
Lindy    54
dtype: int32

In [30]:
ages = {"Ken":5,"Iris":100,"Lindy":95}
s1 = pd.Series(ages)
s1

Ken        5
Iris     100
Lindy     95
dtype: int64

In [31]:
q1 = {'Japan': 80, 'China': 450, 'India': 200, 'USA': 250}
q2 = {'Brazil': 100,'China': 500, 'India': 210,'USA': 260}
sales_Q1 = pd.Series(q1)
sales_Q2 = pd.Series(q2)
sales_Q1

Japan     80
China    450
India    200
USA      250
dtype: int64

In [32]:
sales_Q2

Brazil    100
China     500
India     210
USA       260
dtype: int64

In [33]:
sales_Q1["Japan"]

80

In [34]:
sales_Q2["China"]

500

In [35]:
sales_Q2.iloc[2]

210

In [36]:
sales_Q2.keys()

Index(['Brazil', 'China', 'India', 'USA'], dtype='object')

In [37]:
sales_Q2 * 2

Brazil     200
China     1000
India      420
USA        520
dtype: int64

In [38]:
sales_Q2 / 100

Brazil    1.0
China     5.0
India     2.1
USA       2.6
dtype: float64

In [39]:
sales_Q1 + sales_Q2

Brazil      NaN
China     950.0
India     410.0
Japan       NaN
USA       510.0
dtype: float64

In [42]:
sales_Q1.add(sales_Q2,fill_value=0)

Brazil    100.0
China     950.0
India     410.0
Japan      80.0
USA       510.0
dtype: float64

In [43]:
import pandas as pd
import numpy as np
np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]])

In [46]:
myindex = ["CA","NY","AZ","TX"]
mycolumns = ["JAN","FEB","MAR"]

In [44]:
df = pd.DataFrame(data=mydata)
df

    0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

In [47]:
df = pd.DataFrame(data=mydata,index = myindex,columns=mycolumns)
df

    JAN  FEB  MAR
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   JAN     4 non-null      int32
 1   FEB     4 non-null      int32
 2   MAR     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

In [49]:
df.describe()

             JAN        FEB        MAR
count   4.000000   4.000000   4.000000
mean   70.000000  21.750000  77.000000
std    22.730303  27.657127  10.198039
min    40.000000   4.000000  63.000000
25%    62.500000   7.750000  73.500000
50%    72.500000  10.000000  79.000000
75%    80.000000  24.000000  82.500000
max    95.000000  63.000000  87.000000

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("tips.csv")
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [3]:
df.head(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458

關於此數據集（如果您感興趣）

* 描述
    * 一位服務員在一家餐廳工作幾個月期間記錄了他收到的每一筆小費的信息。他收集了幾個變量：

* 格式
    * 一個包含244行和7個變量的數據框

* 詳細信息
    *账单金额（美元）， 
    * 小費金額（美元），
    * 付款者的性别，
    * 聚會中是否有吸烟者，
    * 一周中的哪一天，
    * 一天中的時間，
    * 聚會的人數。

總共記錄了244筆小費。這些數據在一系列商業統計案例研究中被報告（Bryant & Smith 1995）。

* 參考文獻
    * Bryant, P. G. 和 Smith, M (1995) Practical Data Analysis: Case Studies in Business Statistics. Homewood, IL: Richard D. Irwin Publishing:
    
* 注意：我們創建了一些包含假數據的額外列，包括姓名、信用卡號和付款ID。

In [4]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [5]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [6]:
df.tail(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [7]:
len(df)

244

In [8]:
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [10]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

In [11]:
df["total_bill"]

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [12]:
type(df["total_bill"])

pandas.core.series.Series

In [18]:
tb = df[["total_bill","tip"]]
print(tb)
print(type(tb))

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>

In [20]:
tb = df[["total_bill"]]
tb

     total_bill
0         16.99
1         10.34
2         21.01
3         23.68
4         24.59
..          ...
239       29.03
240       27.18
241       22.67
242       17.82
243       18.78

[244 rows x 1 columns]

In [21]:
df["tip_percentage"] = 100 * df["tip"] / df["total_bill"]

In [25]:
df.head(2)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05

In [23]:
df["price_per_person"] = np.round(df["price_per_person"],2)
df["tip_percentage"] = np.round(df["tip_percentage"],2)

In [24]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68

In [ ]:
newDf = df.drop("tip_percentage",axis=1).head(3)
newDf#有刪除tip_percentage

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458

In [29]:
df.head(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66

In [31]:
df.drop("tip_percentage",axis=1,inplace=True)#inplace=True會刪除df的tip_percentage
df.head(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458