## 作業
```python
def last_four(num):
    pass
```
# 希望傳入一個字串可幫我取得後四碼
# "3560325168603410"

In [2]:
## 作業
def last_four(num):
    return num[-4:]
myStr = "3560325168603410"
mystr = last_four(myStr)
print(mystr)

3410

In [3]:
import pandas as pd
df = pd.read_csv("tips.csv")
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [5]:
def last_four(num):
    return str(num)[-4:]
df["CC Number"].apply(last_four)

0      3410
1      9230
2      1322
3      5994
4      7221
       ...
239    2842
240    5404
241    7196
242    0950
243    8139
Name: CC Number, Length: 244, dtype: object

In [8]:
def yelp(price):
    if price <10:
        return "$"
    elif price >= 10 and price < 30:
        return "$$"
    else:
        return "$$$"
yelp(20)

'$$'

In [10]:
df["Expensive"] = df["total_bill"].apply(yelp)

In [11]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Expensive
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,$$

In [12]:
func = lambda x : x ** 2
func(5)

25

In [13]:
func2 = lambda x:"成年" if x >=18 else "未成年"
print(func2(18))
print(func2(5))

成年
未成年

In [14]:
df["total_bill"].apply(lambda bill:bill*0.18).head(5)

0    3.0582
1    1.8612
2    3.7818
3    4.2624
4    4.4262
Name: total_bill, dtype: float64

In [16]:
def quality(total_bill,tip):
    if tip / total_bill > 0.25:
        return "Generous"
    else:
        return "Other"
print(quality(100,75))

Generous

In [18]:
func1 = lambda df:quality(df["total_bill"],df["tip"])
df["Tip Quality"] = df[["total_bill","tip"]].apply(func1,axis=1)

In [19]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Expensive,Tip Quality
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,$$,Other
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,$$,Other
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,$$,Other
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,$$,Other
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,$$,Other

In [20]:
df.sort_values("tip").head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Expensive,Tip Quality
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,$,Generous
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,$$,Other
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,$,Other
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,$,Other
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,$$,Other

In [21]:
df.sort_values("tip").tail()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Expensive,Tip Quality
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025,$$$,Other
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,$$$,Other
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,$$$,Other
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,$$$,Other
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,$$$,Other

In [22]:
df.sort_values("tip",ascending=False).head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Expensive,Tip Quality
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,$$$,Other
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,$$$,Other
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,$$$,Other
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,$$$,Other
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025,$$$,Other

In [25]:
df.sort_values(["tip","size"]).head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Expensive,Tip Quality
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,$,Generous
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,$,Other
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,$,Other
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,$$,Other
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,$$,Other

In [26]:
df.sort_values(["tip","size"],ascending=[True,False]).head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Expensive,Tip Quality
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,$,Other
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,$$,Other
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,$,Generous
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,$,Other
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,$$,Other

## df.corr() for correlation checks

[Wikipedia on Correlation](https://en.wikipedia.org/wiki/Correlation_and_dependence)

相關係數的含義：

1 表示完全正相關：當一個變量增加時，另一個變量也同樣比例增加

。
-1 表示完全負相關：當一個變量增加時，另一個變量同樣比例減

少。
0 表示沒有線性相關：兩個變量之間沒有線性

關聯。

In [28]:
number_df = df.select_dtypes(include=["number"])
number_df
#corr_matrix = df.corr()

     total_bill   tip  size  price_per_person         CC Number
0         16.99  1.01     2              8.49  3560325168603410
1         10.34  1.66     3              3.45  4478071379779230
2         21.01  3.50     3              7.00  6011812112971322
3         23.68  3.31     2             11.84  4676137647685994
4         24.59  3.61     4              6.15  4832732618637221
..          ...   ...   ...               ...               ...
239       29.03  5.92     3              9.68  5296068606052842
240       27.18  2.00     2             13.59  3506806155565404
241       22.67  2.00     2             11.34  6011891618747196
242       17.82  1.75     2              8.91     4375220550950
243       18.78  3.00     2              9.39  3511451626698139

[244 rows x 5 columns]

In [29]:
corr_matrix = number_df.corr()
corr_matrix

                  total_bill       tip      size  price_per_person  CC Number
total_bill          1.000000  0.675734  0.598315          0.647554   0.104576
tip                 0.675734  1.000000  0.489299          0.347405   0.110857
size                0.598315  0.489299  1.000000         -0.175359  -0.030239
price_per_person    0.647554  0.347405 -0.175359          1.000000   0.135240
CC Number           0.104576  0.110857 -0.030239          0.135240   1.000000

In [31]:
df[["tip","total_bill","price_per_person"]].corr()

                       tip  total_bill  price_per_person
tip               1.000000    0.675734          0.347405
total_bill        0.675734    1.000000          0.647554
price_per_person  0.347405    0.647554          1.000000

In [32]:
df["total_bill"].max()

50.81

In [33]:
df["total_bill"].idxmax()

170

In [36]:
df.iloc[170]

total_bill                     50.81
tip                             10.0
sex                             Male
smoker                           Yes
day                              Sat
time                          Dinner
size                               3
price_per_person               16.94
Payer Name             Gregory Clark
CC Number           5473850968388236
Payment ID                   Sat1954
Expensive                        $$$
Tip Quality                    Other
Name: 170, dtype: object

In [34]:
df["total_bill"].min()

3.07

In [35]:
df["total_bill"].idxmin()

67

In [37]:
df.iloc[67]

total_bill                      3.07
tip                              1.0
sex                           Female
smoker                           Yes
day                              Sat
time                          Dinner
size                               1
price_per_person                3.07
Payer Name             Tiffany Brock
CC Number           4359488526995267
Payment ID                   Sat3455
Expensive                          $
Tip Quality                 Generous
Name: 67, dtype: object

In [38]:
df["sex"].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [39]:
df["smoker"].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [ ]:
df["smoker"].replace(to_replace="No",value="N").head()

0    N
1    N
2    N
3    N
4    N
Name: smoker, dtype: object

In [43]:
usize = df["size"].unique()
usize.sort()
usize

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [44]:
#time
myArray = df["time"].unique()
myArray

array(['Dinner', 'Lunch'], dtype=object)

In [46]:
print(df["smoker"].value_counts())

df["smoker"] = df["smoker"].replace({
    "Yes": "Y",
    "No": "N"
})

smoker
N    151
Y     93
Name: count, dtype: int64

In [47]:
def change_time(time):
    if time == "Dinner":
        return "D"
    else:
        return "L"
df["time"].apply(change_time).value_counts()

time
D    176
L     68
Name: count, dtype: int64

In [48]:
df["time"].apply(lambda time:"D" if time=="Dinner" else "L").value_counts()

time
D    176
L     68
Name: count, dtype: int64

In [49]:
myDict = {"Dinner":"D","Lunch":"L"}
df["time"].map(myDict).value_counts()

time
D    176
L     68
Name: count, dtype: int64

In [50]:
fruits = ["apple","banana","cherry"]
myDict = {}
for i in range(len(fruits)):
    myDict[fruits[i]] = i
myDict

{'apple': 0, 'banana': 1, 'cherry': 2}